### ISSUE TITLE
PlinkFileFormat fails with error "Cannot seek to a negative offset" 

### ISSUE THREAD

**Issue by eric-czech** [projectglow/glow#133]
Hi, I was working some 1kg data and saw that the PLINK reader is having an issue I can't quite pinpoint the cause for.  I'm hoping it might be more immediately obvious for someone more familiar with that code.

I'm fetching a vcf dataset and converting to PLINK as follows:

```bash
wget ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/release/20100804/ALL.2of4intersection.20100804.genotypes.vcf.gz
plink --vcf ALL.2of4intersection.20100804.genotypes.vcf.gz \
  --make-bed --out ALL.2of4intersection.20100804.genotypes
```

When reading this via Glow:

```scala
spark
  .read.format("plink")
  .load("ALL.2of4intersection.20100804.genotypes.bed")
  .count
```

I encounter this ([full stack trace](https://github.com/projectglow/glow/files/4071878/stacktrace.txt)):

```
20/01/16 13:14:54 INFO PlinkFileFormat$: hlsUsage:[plinkRead,{"includeSampleIds":true,"mergeFidIid":true}]
20/01/16 13:15:02 INFO PlinkFileFormat: Reading variants [0, 849480]
20/01/16 13:15:02 INFO PlinkFileFormat: Reading variants [849480, 1698959]
20/01/16 13:15:02 INFO PlinkFileFormat: Reading variants [1698959, 2548438]
20/01/16 13:15:06 INFO PlinkFileFormat: Reading variants [2548438, 3397918]
20/01/16 13:15:06 INFO PlinkFileFormat: Reading variants [3397918, 4247397]
20/01/16 13:15:06 INFO PlinkFileFormat: Reading variants [4247397, 5096876]
20/01/16 13:15:07 INFO PlinkFileFormat: Reading variants [5096876, 5946356]
20/01/16 13:15:07 INFO PlinkFileFormat: Reading variants [5946356, 6795835]
20/01/16 13:15:07 INFO PlinkFileFormat: Reading variants [6795835, 7645314]
20/01/16 13:15:07 INFO PlinkFileFormat: Reading variants [8494793, 9344273]
20/01/16 13:15:07 INFO PlinkFileFormat: Reading variants [9344273, 10193752]
20/01/16 13:15:07 INFO PlinkFileFormat: Reading variants [7645314, 8494793]
20/01/16 13:15:07 INFO PlinkFileFormat: Reading variants [10193752, 11043231]
20/01/16 13:15:08 INFO PlinkFileFormat: Reading variants [11043231, 11892711]
20/01/16 13:15:08 INFO PlinkFileFormat: Reading variants [11892711, 12742190]
20/01/16 13:15:08 INFO PlinkFileFormat: Reading variants [12742190, 13591669]
20/01/16 13:15:17 INFO PlinkFileFormat: Reading variants [25484379, 52671826]
20/01/16 13:15:17 ERROR Executor: Exception in task 30.0 in stage 0.0 (TID 30)
java.io.EOFException: Cannot seek to a negative offset
	at org.apache.hadoop.fs.FSInputChecker.seek(FSInputChecker.java:399)
	at org.apache.hadoop.fs.FSDataInputStream.seek(FSDataInputStream.java:62)
	at org.apache.hadoop.fs.ChecksumFileSystem$FSDataBoundedInputStream.seek(ChecksumFileSystem.java:330)
	at io.projectglow.plink.PlinkFileFormat$$anonfun$buildReader$1.apply(PlinkFileFormat.scala:118)
	at io.projectglow.plink.PlinkFileFormat$$anonfun$buildReader$1.apply(PlinkFileFormat.scala:90)
	at org.apache.spark.sql.execution.datasources.FileFormat$$anon$1.apply(FileFormat.scala:148)
```
My first thought was that this might be related to the fact that many of the rsids are missing (i.e. "."), but that doesn't seem to be the issue.  Hail can read the data w/o problems and reports that ~10M of ~25M are missing.  Hail also shows that the following transformation to add unique ids results in a dataset with all unique rsids that still fails with the same error above when read by Glow:

```bash
plink --bfile ALL.2of4intersection.20100804.genotypes \
--set-missing-var-ids @:#[b37]\$1,\$2 --make-bed \
--out ALL.2of4intersection.20100804.genotypes.uniqids
```

It is worth nothing though that after removing variants and samples with low call rates and MAF via PLINK, I can read the result successfully w/ Glow:

```scala
spark.read
  .format("plink")
  // This dataset contains only ~5.8M variants out of the original ~25M
  .load("ALL.2of4intersection.20100804.genotypes.uniqids.filtered.bed")
  .drop("genotypes").show(5)

+----------+-----------------+--------+-----+-----+---------------+----------------+
|contigName|            names|position|start|  end|referenceAllele|alternateAlleles|
+----------+-----------------+--------+-----+-----+---------------+----------------+
|         1|     [rs58108140]|     0.0|10582|10583|              G|             [A]|
|         1|[1:11508[b37]A,G]|     0.0|11507|11508|              G|             [A]|
|         1|[1:15820[b37]G,T]|     0.0|15819|15820|              G|             [T]|
|         1|[1:16257[b37]C,G]|     0.0|16256|16257|              G|             [C]|
|         1|[1:16378[b37]C,T]|     0.0|16377|16378|              C|             [T]|
+----------+-----------------+--------+-----+-----+---------------+----------------+
```

Does anybody have thoughts on what else could cause this?

*environment*: Spark 2.4.4, Glow 0.20

**Comment by eric-czech** [comment]
Thanks for picking this up @karenfeng!  I was just about to mention that I found it to be an overflow at [getVariantStart](https://github.com/projectglow/glow/blame/6131e6f2e5f802156749c7b9f2c125c9c1b84482/core/src/main/scala/io/projectglow/plink/PlinkFileFormat.scala#L268) but I see you've already got a PR in the works.

**Comment by karenfeng** [comment]
That was the issue I saw too; thanks @eric-czech! Addressed in https://github.com/projectglow/glow/pull/135.
