### ISSUE TITLE
NoClassDefFoundError: org/apache/logging/log4j/core/appender/AbstractAppender

### ISSUE THREAD

**Issue by Hoeze** [projectglow/glow#190]
I encountered a problem with commit 17009690b8323b243aa9876fc3a2e53a06356efb as assembly jar. This is working with `io.projectglow:glow_2.11:0.3.0`.
Am I missing some classes in my assembly jar?

Please just ignore if you do not want to support bleeding edge problems :smiley: 

<details>

```
tests/test_glow.py::test_read_vcf 20/04/17 00:44:47 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
                                                                                
tests/test_glow.py:21 (test_read_vcf)
glow_session = <pyspark.sql.session.SparkSession object at 0x7f4dfad579d0>

    def test_read_vcf(glow_session: pyspark.sql.SparkSession):
        path = "resources/glow_example.vcf"
        # ref_genome =
    
        df = (
            glow_session
                .read
                .format('vcf')
                .option("includeSampleIds", True)
                .load(path)
        )
    
        # %%
    
        # normalized_variants_df = glow.transform(
        #     "normalize_variants",
        #     df,
        #     reference_genome_path=ref_genome,
        #     mode='split_and_normalize'
        # )
        # df = glow_session.read.format("parquet").load("resources/example.vcf")
>       displayHead(df)

tests/test_glow.py:43: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
firefly/utils.py:18: in displayHead
    return df.limit(nrows).toPandas()
/opt/anaconda/envs/default/lib/python3.7/site-packages/pyspark/sql/dataframe.py:2226: in toPandas
    pdf = pd.DataFrame.from_records(self.collect(), columns=self.columns)
/opt/anaconda/envs/default/lib/python3.7/site-packages/pyspark/sql/dataframe.py:563: in collect
    sock_info = self._jdf.collectToPython()
/opt/anaconda/envs/default/lib/python3.7/site-packages/py4j/java_gateway.py:1286: in __call__
    answer, self.gateway_client, self.target_id, self.name)
/opt/anaconda/envs/default/lib/python3.7/site-packages/pyspark/sql/utils.py:98: in deco
    return f(*a, **kw)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

answer = 'xro80'
gateway_client = <py4j.java_gateway.GatewayClient object at 0x7f4dfad383d0>
target_id = 'o73', name = 'collectToPython'

    def get_return_value(answer, gateway_client, target_id=None, name=None):
        """Converts an answer received from the Java gateway into a Python object.
    
        For example, string representation of integers are converted to Python
        integer, string representation of objects are converted to JavaObject
        instances, etc.
    
        :param answer: the string returned by the Java gateway
        :param gateway_client: the gateway client used to communicate with the Java
            Gateway. Only necessary if the answer is a reference (e.g., object,
            list, map)
        :param target_id: the name of the object from which the answer comes from
            (e.g., *object1* in `object1.hello()`). Optional.
        :param name: the name of the member from which the answer comes from
            (e.g., *hello* in `object1.hello()`). Optional.
        """
        if is_error(answer)[0]:
            if len(answer) > 1:
                type = answer[1]
                value = OUTPUT_CONVERTER[type](answer[2:], gateway_client)
                if answer[1] == REFERENCE_TYPE:
                    raise Py4JJavaError(
                        "An error occurred while calling {0}{1}{2}.\n".
>                       format(target_id, ".", name), value)
E                   py4j.protocol.Py4JJavaError: An error occurred while calling o73.collectToPython.
E                   : java.lang.NoClassDefFoundError: org/apache/logging/log4j/core/appender/AbstractAppender
E                   	at java.lang.ClassLoader.defineClass1(Native Method)
E                   	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
E                   	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
E                   	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
E                   	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
E                   	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
E                   	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
E                   	at java.security.AccessController.doPrivileged(Native Method)
E                   	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
E                   	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
E                   	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
E                   	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
E                   	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
E                   	at org.apache.logging.log4j.core.config.plugins.util.PluginRegistry.decodeCacheFiles(PluginRegistry.java:181)
E                   	at org.apache.logging.log4j.core.config.plugins.util.PluginRegistry.loadFromMainClassLoader(PluginRegistry.java:119)
E                   	at org.apache.logging.log4j.core.config.plugins.util.PluginManager.collectPlugins(PluginManager.java:132)
E                   	at org.apache.logging.log4j.core.pattern.PatternParser.<init>(PatternParser.java:129)
E                   	at org.apache.logging.log4j.core.pattern.PatternParser.<init>(PatternParser.java:110)
E                   	at org.apache.logging.log4j.core.layout.PatternLayout.createPatternParser(PatternLayout.java:216)
E                   	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:128)
E                   	at org.apache.logging.log4j.core.layout.PatternLayout.<init>(PatternLayout.java:56)
E                   	at org.apache.logging.log4j.core.layout.PatternLayout$Builder.build(PatternLayout.java:376)
E                   	at org.apache.logging.log4j.core.config.DefaultConfiguration.<init>(DefaultConfiguration.java:58)
E                   	at org.apache.logging.log4j.core.LoggerContext.<init>(LoggerContext.java:70)
E                   	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:145)
E                   	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:70)
E                   	at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:57)
E                   	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:142)
E                   	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:41)
E                   	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:175)
E                   	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:426)
E                   	at org.broadinstitute.hellbender.utils.Utils.<clinit>(Utils.java:77)
E                   	at org.broadinstitute.hellbender.utils.SimpleInterval.validatePositions(SimpleInterval.java:61)
E                   	at org.broadinstitute.hellbender.utils.SimpleInterval.<init>(SimpleInterval.java:37)
E                   	at io.projectglow.vcf.FilterInterval.liftedTree1$1(TabixIndexHelper.scala:93)
E                   	at io.projectglow.vcf.FilterInterval.<init>(TabixIndexHelper.scala:92)
E                   	at io.projectglow.vcf.TabixIndexHelper$.parseFilter(TabixIndexHelper.scala:186)
E                   	at io.projectglow.vcf.TabixIndexHelper$.makeFilteredInterval(TabixIndexHelper.scala:402)
E                   	at io.projectglow.vcf.VCFFileFormat.buildReader(VCFFileFormat.scala:147)
E                   	at org.apache.spark.sql.execution.datasources.FileFormat.buildReaderWithPartitionValues(FileFormat.scala:130)
E                   	at org.apache.spark.sql.execution.datasources.FileFormat.buildReaderWithPartitionValues$(FileFormat.scala:121)
E                   	at org.apache.spark.sql.execution.datasources.TextBasedFileFormat.buildReaderWithPartitionValues(FileFormat.scala:170)
E                   	at org.apache.spark.sql.execution.FileSourceScanExec.inputRDD$lzycompute(DataSourceScanExec.scala:394)
E                   	at org.apache.spark.sql.execution.FileSourceScanExec.inputRDD(DataSourceScanExec.scala:385)
E                   	at org.apache.spark.sql.execution.FileSourceScanExec.doExecute(DataSourceScanExec.scala:468)
E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:173)
E                   	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:211)
E                   	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
E                   	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:208)
E                   	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:169)
E                   	at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:313)
E                   	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:405)
E                   	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:47)
E                   	at org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:3310)
E                   	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3472)
E                   	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$4(SQLExecution.scala:100)
E                   	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:160)
E                   	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:87)
E                   	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3468)
E                   	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3307)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
E                   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
E                   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
E                   	at java.lang.reflect.Method.invoke(Method.java:498)
E                   	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
E                   	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
E                   	at py4j.Gateway.invoke(Gateway.java:282)
E                   	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
E                   	at py4j.commands.CallCommand.execute(CallCommand.java:79)
E                   	at py4j.GatewayConnection.run(GatewayConnection.java:238)
E                   	at java.lang.Thread.run(Thread.java:748)
E                   Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.core.appender.AbstractAppender
E                   	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
E                   	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
E                   	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
E                   	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
E                   	... 71 more

/opt/anaconda/envs/default/lib/python3.7/site-packages/py4j/protocol.py:328: Py4JJavaError

Assertion failed

```

</details>

**Comment by henrydavidge** [comment]
@Hoeze it looks like you're missing log4j2, which is a transitive dependency of GATK. Perhaps you're excluding it in your assembly build?

In case it's relevant for your use case, in Databricks we forward GATK's log4j logs to log4j1.2 (messy, I know) using [https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-to-slf4j](this package).

Btw, in the next release of Glow, we're planning on removing our dependency of GATK. That will significantly clean up the transitive dependencies since GATK pulls in a bunch of libraries.

**Comment by Hoeze** [comment]
Thanks for your answer @henrydavidge .

> @Hoeze it looks like you're missing log4j2, which is a transitive dependency of GATK. Perhaps you're excluding it in your assembly build?

Not actively. I built the jar using the following command:
`sbt core_2_12/assembly`

Does it make sense to directly include GATK as a dependency to Spark?

**Comment by Hoeze** [comment]
I checked and there is actually `org/apache/logging/log4j/core/appender/AbstractAppender` in the glow-assembly.jar.

Changing the option
```
spark.jars: jars/glow-assembly-0.3.1-SNAPSHOT.jar
```
to
```
spark.driver.extraClassPath: jars/glow-assembly-0.3.1-SNAPSHOT.jar
```
actually solved my problem.

Does this mean there is a package collision with core Spark packages?

**Comment by henrydavidge** [comment]
@Hoeze Apologies for the delay here.

I don't full understand the details, but this appears to be a strange classloader interaction between Spark and log4j. As I understand it, Spark tries to separate the classloader used for user dependencies and the classloader used for Spark itself. It looks like log4j has circumvented that separation and is trying to load a plugin from the system classloader, which doesn't work because the log4j jars are in the user classloader. 

I'm going to go ahead and close this issue since there's a workaround, and @kianfar77 is in the process of removing the GATK dependency, which will also allow us to drop log4j2 as a direct dependency.
