### ISSUE TITLE
Transitive dependencies of htsjdk:2.20.1 unresolvable with sbt

### ISSUE THREAD

**Issue by heuermh** [projectglow/glow#31]
```
sbt:glow> test
[info] Updating core...
[info] Checking 35 Scala sources...
[info] Checking 80 Scala sources...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.apache.commons#commons-jexl;2.1.1: org.apache.commons#commons-jexl;2.1.1!commons-jexl.pom(pom.original) origin location must be absolute: file:/Users/foo/.m2/repository/org/apache/commons/commons-jexl/2.1.1/commons-jexl-2.1.1.pom
[warn] 	:: org.xerial.snappy#snappy-java;1.1.4: org.xerial.snappy#snappy-java;1.1.4!snappy-java.pom(pom.original) origin location must be absolute: file:/Users/foo/.m2/repository/org/xerial/snappy/snappy-java/1.1.4/snappy-java-1.1.4.pom
[warn] 	:: gov.nih.nlm.ncbi#ngs-java;2.9.0: gov.nih.nlm.ncbi#ngs-java;2.9.0!ngs-java.pom(pom.original) origin location must be absolute: file:/Users/foo/.m2/repository/gov/nih/nlm/ncbi/ngs-java/2.9.0/ngs-java-2.9.0.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.apache.commons:commons-jexl:2.1.1
[warn] 		  +- com.github.samtools:htsjdk:2.20.1
[warn] 		  +- org.seqdoop:hadoop-bam:7.9.2
[warn] 		  +- org.bdgenomics.adam:adam-core-spark2_2.11:0.28.0
[warn] 		  +- org.bdgenomics.adam:adam-apis-spark2_2.11:0.28.0 (working/glow/build.sbt#L129)
[warn] 		  +- io.projectglow:glow_2.11:0.2.0-SNAPSHOT
[warn] 		org.xerial.snappy:snappy-java:1.1.4
[warn] 		  +- com.github.samtools:htsjdk:2.20.1
[warn] 		  +- org.seqdoop:hadoop-bam:7.9.2
[warn] 		  +- org.bdgenomics.adam:adam-core-spark2_2.11:0.28.0
[warn] 		  +- org.bdgenomics.adam:adam-apis-spark2_2.11:0.28.0 (working/glow/build.sbt#L129)
[warn] 		  +- io.projectglow:glow_2.11:0.2.0-SNAPSHOT
[warn] 		gov.nih.nlm.ncbi:ngs-java:2.9.0
[warn] 		  +- com.github.samtools:htsjdk:2.20.1
[warn] 		  +- org.seqdoop:hadoop-bam:7.9.2
[warn] 		  +- org.bdgenomics.adam:adam-core-spark2_2.11:0.28.0
[warn] 		  +- org.bdgenomics.adam:adam-apis-spark2_2.11:0.28.0 (working/glow/build.sbt#L129)
[warn] 		  +- io.projectglow:glow_2.11:0.2.0-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.apache.commons#commons-jexl;2.1.1: org.apache.commons#commons-jexl;2.1.1!commons-jexl.pom(pom.original) origin location must be absolute: file:/Users/foo/.m2/repository/org/apache/commons/commons-jexl/2.1.1/commons-jexl-2.1.1.pom
[error] unresolved dependency: org.xerial.snappy#snappy-java;1.1.4: org.xerial.snappy#snappy-java;1.1.4!snappy-java.pom(pom.original) origin location must be absolute: file:/Users/foo/.m2/repository/org/xerial/snappy/snappy-java/1.1.4/snappy-java-1.1.4.pom
[error] unresolved dependency: gov.nih.nlm.ncbi#ngs-java;2.9.0: gov.nih.nlm.ncbi#ngs-java;2.9.0!ngs-java.pom(pom.original) origin location must be absolute: file:/Users/foo/.m2/repository/gov/nih/nlm/ncbi/ngs-java/2.9.0/ngs-java-2.9.0.pom
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2561)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by heuermh** [comment]
Fixed by removing the Ivy cache, `rm -Rf ~/.ivy2`.  Sorry for the noise.
