### ISSUE TITLE
import glow throws error: module 'numpy' has no attribute 'unicode'. Did you mean: 'unicode_'?

### ISSUE THREAD

**Issue by bounaux** [projectglow/glow#539]
I'm running databricks on Azure with Python v3.10.12. First line of import glow immediately throw error, here is trace, any idea pls?

SparkSession available as 'spark'.
>>> import glow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/glow/__init__.py", line 30, in <module>
    from .wgr import *  # For backwards compatibility. Avoid showing this import in docs.
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/glow/wgr/__init__.py", line 15, in <module>
    from glow.wgr.ridge_reduction import *
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/glow/wgr/ridge_reduction.py", line 15, in <module>
    from .ridge_udfs import *
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/glow/wgr/ridge_udfs.py", line 15, in <module>
    from glow.wgr.model_functions import *
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/glow/wgr/model_functions.py", line 25, in <module>
    from nptyping import Float, Int, NDArray
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/nptyping/__init__.py", line 2, in <module>
    from nptyping.functions._get_type import get_type
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/nptyping/functions/_get_type.py", line 23, in <module>
    from nptyping.types._unicode import Unicode
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/nptyping/types/_unicode.py", line 30, in <module>
    class Unicode(NPType, numpy.unicode, metaclass=_UnicodeMeta):
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'unicode'. Did you mean: 'unicode_'?
>>>

**Comment by bounaux** [comment]
Did you mean: 'unicode_'?

**Comment by henrydavidge** [comment]
I believe that this is occurring because the `numpy` and `npyping` versions are not compatible. We'll have a new release soon with a looser `nptyping` version requirement. Until then, you can build artifacts from source.
