### ISSUE TITLE
Support for conda?

### ISSUE THREAD

**Issue by Hoeze** [projectglow/glow#56]
Are there any plans to support conda?

**Comment by henrydavidge** [comment]
@Hoeze you can always include pip packages in a conda environment file. Is there an advantage to publishing directly to conda?

**Comment by Hoeze** [comment]
@henrydavidge Yes, conda does resolve dependency conflicts.
If you install glow via pip, it does not care about dependencies of other packages. Pip will just overwrite package version if it thinks to need them.
Using pip is therefore quite dangerous. It can completely mess up your whole environment.

As an example, following your current installation instructions does not work:
```
> pip install pyspark==2.4.2
Successfully built pyspark
Installing collected packages: py4j, pyspark
Successfully installed py4j-0.10.7 pyspark-2.4.2
> pip install glow.py
Installing collected packages: typeguard, glow.py
Successfully installed glow.py-0.1.0 typeguard-2.5.0

> pyspark --packages io.projectglow:glow_2.11:0.1.2
Python 3.8.0 | packaged by conda-forge | (default, Nov  6 2019, 23:20:36) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "/opt/anaconda/envs/glow-test2/lib/python3.8/site-packages/pyspark/python/pyspark/shell.py", line 31, in <module>
    from pyspark import SparkConf
  File "/opt/anaconda/envs/glow-test2/lib/python3.8/site-packages/pyspark/__init__.py", line 51, in <module>
    from pyspark.context import SparkContext
  File "/opt/anaconda/envs/glow-test2/lib/python3.8/site-packages/pyspark/context.py", line 31, in <module>
    from pyspark import accumulators
  File "/opt/anaconda/envs/glow-test2/lib/python3.8/site-packages/pyspark/accumulators.py", line 97, in <module>
    from pyspark.serializers import read_int, PickleSerializer
  File "/opt/anaconda/envs/glow-test2/lib/python3.8/site-packages/pyspark/serializers.py", line 71, in <module>
    from pyspark import cloudpickle
  File "/opt/anaconda/envs/glow-test2/lib/python3.8/site-packages/pyspark/cloudpickle.py", line 145, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/opt/anaconda/envs/glow-test2/lib/python3.8/site-packages/pyspark/cloudpickle.py", line 126, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)
```

If you instead do the following:
```
> conda install pyspark
# installs pyspark-2.4.4, downgrades to python 3.7.5, ...
pip install glow.py
```
you get a working environment since conda resolves incompatible python versions.

[Please have a look here](https://stackoverflow.com/a/20994790/2219819) for more details

**Comment by henrydavidge** [comment]
Got it. We'll look into this in the nearish future.

**Comment by agoddijn** [comment]
👍  on this. Would be great to have this available on conda forge

**Comment by henrydavidge** [comment]
@agoddijn @Hoeze FYI the upcoming 1.0 release will also be published to conda.
